### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by mkb2091** [DataMaster-2501/DataMaster-Android-AdBlock-Hosts#1]
I found a few sites that are blocked in the hosts file, but they are both valid first-party domains that users might want to visit, so I believe they are false positives:
yoast.com
www.yoast.com
alexa.com
www.alexa.com
entireweb.com
www.entireweb.com

virustotalcloud.appspot.com - is needed for virustotal desktop file upload

**Comment by DataMaster-2501** [comment]
I am sry about that.
When dealing with 271674 lines things get a bit crazy.
I'm not sure how yoast.com got in there. (I'm a fan of yoast)
So yoast.com will be removed.
As for virustotalcloud.appspot.com
I did not mean to add "virustotalcloud.appspot.com" but appspot.com hosts so many ads companies junk that it was just easier to just add all of it & over time pull out the one's that are not ads junk. (looks like this part needs more work)
So I will remove:
yoast.com
virustotalcloud.appspot.com
In this next update that I'm doing today.
As for the others they will not be removed because of what they are.
Remember this list blocks Ads/Marketing services & Analytics/Tracking Services etc...
Thank you for letting me know about:
yoast.com
virustotalcloud.appspot.com

**Comment by DataMaster-2501** [comment]
Fixed in v1.3
Do let me know if you have any other problems with the list.
