### ISSUE TITLE
connectivitycheck.platform.hicloud.com

### ISSUE THREAD

**Issue by whoot** [DataMaster-2501/DataMaster-Android-AdBlock-Hosts#14]
Seems to be a false positive, as it restricts downloads of Huawei apps in the Google Play Store.

**Comment by DataMaster-2501** [comment]
No not a false positive.
Due to the fact Huawei has violations in Cybersecurity, Data Privacy, intellectual property, and human rights
I have blocked all Huawei domains & all domains owned by Huawei.
My list is not just about blocking Ads but it is also about Data Privacy
& with the fact that Huawei & Chinese government are one
I sure as all hell don't trust them.

The domain is not removed
end of line

**Comment by whoot** [comment]
Alright, keep calm. lol

**Comment by DataMaster-2501** [comment]
sry sometimes I get on my Soapbox lol😁
