### ISSUE TITLE
Officially giving up on this list - Seems to be abandoned.

### ISSUE THREAD

**Issue by p1r473** [DataMaster-2501/DataMaster-Android-AdBlock-Hosts#22]
Officially giving up on this list - Seems to be abandoned.
@DataMaster-2501

**Comment by DataMaster-2501** [comment]
I'm deeply sry for not replying back to the open issue people have been posting about my list but due to the covid19 & the economic downturn as well as many other bad things going on in my life I've not had the time nor the ability to work on or keep up with my list. I am planning on resuming work on this list in Dec-2020 if things don't worst for me. I'm sry for the inconvenience

**Comment by p1r473** [comment]
No problem, glad to see its updated now
